"""added 'content_html' into Post model

Revision ID: 4b4e8e7ccda0
Revises: be53b7fe928b
Create Date: 2023-10-30 12:18:16.427752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4e8e7ccda0'
down_revision = 'be53b7fe928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('content_html')

    # ### end Alembic commands ###
